Repository CSID-DGU/2024-2-DSCD-talkingPotato-1, pull requests merged in 2024-12, with the labels that each got.

#34 ✨ Feature - Medication, Schedule, User API
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/exception/error/ErrorCode.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/controller/command/MedicationCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/controller/command/ScheduleCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/controller/query/ScheduleQueryV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/domain/mysql/Medication.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/domain/mysql/Schedule.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/request/CreateMedicationDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/request/CreateScheduleDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/request/UpdateMedicationDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/response/ReadScheduleSummaryDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/response/ReadScheduleWithTimeDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/repository/mysql/MedicationRepository.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/repository/mysql/ScheduleRepository.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/CreateMedicationService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/CreateScheduleService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/DeleteScheduleService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/ReadScheduleSummaryService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/ReadScheduleWithTimeService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/UpdateMedicationService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/CreateMedicationUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/CreateScheduleUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/DeleteScheduleUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/ReadScheduleSummaryUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/ReadScheduleWithTimeUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/UpdateMedicationUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/controller/.persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/controller/command/UserCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/controller/query/UserQueryV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/domain/type/ETime.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/dto/.persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/dto/request/UpdateUserNotificationTimeDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/dto/response/ReadUserDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/service/.persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/service/ReadUserService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/service/UpdateUserNotificationTimeService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/usecase/.persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/usecase/ReadUserUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/usecase/UpdateUserNotificationTimeUseCase.java
Labels: feature ✨

#36 ✨ Feature - API Server CI/CD
  .github/workflows/api-server.yaml
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/security/controller/command/AuthCommandController.java
Labels: feature ✨

#37 🚑 Hot Fix - CICD Branch Error
  .github/workflows/api-server.yaml
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/security/controller/command/AuthCommandController.java
Labels: hot fix 🚑

#38 🚑 Hot Fix - CICD Path Error
  .github/workflows/api-server.yaml
  server-api/Dockerfile
Labels: hot fix 🚑

#44 🐛 Fix - Exception Handler Missing Error
  .github/workflows/api-server.yaml
  server-api/bin/main/META-INF/services/org.hibernate.boot.model.FunctionContributor
  server-api/bin/main/application.yml
  server-api/bin/main/org/dongguk/dscd/wooahan/api/core/listener/persistent
  server-api/bin/main/org/dongguk/dscd/wooahan/api/expert/controller/.persistent
  server-api/bin/main/org/dongguk/dscd/wooahan/api/expert/domain/type/.persistent
  server-api/bin/main/org/dongguk/dscd/wooahan/api/expert/dto/.persistent
  server-api/bin/main/org/dongguk/dscd/wooahan/api/expert/service/.persistent
  server-api/bin/main/org/dongguk/dscd/wooahan/api/expert/usecase/.persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/controller/command/ArticleCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/exception/handler/HttpGlobalExceptionHandler.java
Labels: fix 🐛

#46 🚑 Hot Fix - Json Property Mistake
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/dto/ResponseDto.java
Labels: hot fix 🚑

#45 ✨ Feature - Additional APIs
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/controller/query/MedicationQueryV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/dto/response/ReadUserMedicationListDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/ReadUserMedicationListService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/usecase/ReadUserMedicationListUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/controller/query/QuestionQueryV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/dto/projection/ReadUserQuestionListProjection.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/dto/response/ReadUserQuestionListDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/repository/mysql/custom/QuestionRepositoryCustom.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/repository/mysql/custom/QuestionRepositoryCustomImpl.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/service/ReadUserQuestionListService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/usecase/ReadUserQuestionListUseCase.java
Labels: feature ✨

#48 ✨ Feature - Additional User APIs
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/controller/command/ArticleCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/controller/command/UserCommandV1Controller.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/dto/request/UpdateUserDeviceTokenDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/dto/request/UpdateUserNotificationStatusDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/service/UpdateUserDeviceTokenService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/service/UpdateUserNotificationStatusService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/usecase/UpdateUserDeviceTokenUseCase.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/usecase/UpdateUserNotificationStatusUseCase.java
Labels: feature ✨

#53 🎨 Refactor - Update Medication API, Read Article List API
  server-api/build.gradle
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/dto/response/ReadArticleListDto.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/repository/mysql/custom/ArticleRepositoryCustomImpl.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/service/ReadArticleListService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/service/UpdateMedicationService.java
Labels: refactor 🎨

#55 🐛 Fix - Read Article List API Error
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/service/ReadArticleListService.java
Labels: hot fix 🚑

#56 🚑 HotFix - Medication, Schedule Mapping with Cascade
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/domain/mysql/Medication.java
Labels: hot fix 🚑

#57 ✨ Feature - FCM Notification
  server-api/build.gradle
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/config/FirebaseConfig.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/notification/controller/NotificationController.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/notification/service/NotificationService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/repository/mysql/UserRepository.java
Labels: feature ✨

#59 ✨ Feature - STT, TTS Correction API
  server-llm/.dockerignore
  server-llm/.gitignore
  server-llm/Dockerfile
  server-llm/correction/__init__.py
  server-llm/correction/admin.py
  server-llm/correction/apps.py
  server-llm/correction/migrations/__init__.py
  server-llm/correction/models.py
  server-llm/correction/service.py
  server-llm/correction/tests.py
  server-llm/correction/views.py
  server-llm/generation/__init__.py
  server-llm/generation/admin.py
  server-llm/generation/apps.py
  server-llm/generation/migrations/__init__.py
  server-llm/generation/models.py
  server-llm/generation/tests.py
  server-llm/generation/views.py
  server-llm/manage.py
  server-llm/prompt_engineering.ipynb
  server-llm/requirements.txt
  server-llm/wooahan/__init__.py
  server-llm/wooahan/asgi.py
  server-llm/wooahan/settings.py
  server-llm/wooahan/urls.py
  server-llm/wooahan/wsgi.py
Labels: feature ✨

#61 🐛 Fix - API Server CI/CD Using Github Action
  .github/workflows/api-server.yaml
Labels: fix 🐛

#63 ✨ Feature - STT/TTS API Connection
  client-app/ios/Runner/Info.plist
  client-app/lib/app/config/app_dependence.dart
  client-app/lib/data/provider/analysis/analysis_remote_provider.dart
  client-app/lib/data/provider/analysis/analysis_remote_provider_impl.dart
  client-app/lib/data/provider/analysis/image_analysis_remote_provider.dart
  client-app/lib/data/provider/analysis/language_analysis_remote_provider.dart
  client-app/lib/data/provider/analysis/language_analysis_remote_provider_impl.dart
  client-app/lib/data/provider/correction/correction_remote_provider.dart
  client-app/lib/data/provider/correction/correction_remote_provider_impl.dart
  client-app/lib/data/repository/analysis/analysis_repository_impl.dart
  client-app/lib/data/repository/correction/correction_repository_impl.dart
  client-app/lib/domain/condition/analysis/analysis_speech_condition.dart
  client-app/lib/domain/condition/correction/correct_document_text_condition.dart
  client-app/lib/domain/condition/correction/correct_speech_text_condition.dart
  client-app/lib/domain/repository/analysis/analysis_repository.dart
  client-app/lib/domain/repository/correction/correction_repository.dart
  client-app/lib/domain/usecase/anlaysis/analysis_document_use_case.dart
  client-app/lib/domain/usecase/anlaysis/analysis_speech_use_case.dart
  client-app/lib/domain/usecase/correction/correct_document_text_use_case.dart
  client-app/lib/domain/usecase/correction/correct_speech_text_use_case.dart
  client-app/lib/presentation/view/speech_to_text_converter/fragment/complete_speech_analysis_fragment.dart
  client-app/lib/presentation/view/text_to_speech_converter/fragment/complete_text_analysis_fragment.dart
  client-app/lib/presentation/view_model/speech_to_text_converter/speech_to_text_converter_binding.dart
  client-app/lib/presentation/view_model/speech_to_text_converter/speech_to_text_converter_view_model.dart
  client-app/lib/presentation/view_model/text_to_speech_converter/text_to_speech_converter_binding.dart
  client-app/lib/presentation/view_model/text_to_speech_converter/text_to_speech_converter_view_model.dart
  client-app/pubspec.yaml
  server-llm/correction/views.py
Labels: feature ✨

#65 ✨ Feature - STT/TTS
  client-app/ios/Podfile.lock
  client-app/lib/core/provider/base_connect.dart
  client-app/lib/domain/usecase/comment/create_article_comment_use_case.dart
  client-app/lib/domain/usecase/question/create_question_use_case.dart
  client-app/lib/presentation/view/article/searching/article_searching_screen.dart
  client-app/lib/presentation/view/article/searching/widget/article_result/article_result_view.dart
  client-app/lib/presentation/view/article/searching/widget/article_search_term_field/article_search_term_field.dart
  client-app/lib/presentation/view/comment/adding/comment_adding_screen.dart
  client-app/lib/presentation/view/comment/adding/widget/comment_input_field/comment_input_field.dart
  client-app/lib/presentation/view/comment/adding/widget/comment_speech_button/comment_speech_button.dart
  client-app/lib/presentation/view/question/adding/question_adding_screen.dart
  client-app/lib/presentation/view/question/adding/widget/question_input_field/question_input_field.dart
  client-app/lib/presentation/view/question/adding/widget/question_speech_button/question_speech_button.dart
  client-app/lib/presentation/view/question/detail/widget/answer_card/component/answer_default_item_view.dart
  client-app/lib/presentation/view/question/searching/question_searching_screen.dart
  client-app/lib/presentation/view/question/searching/widget/question_result/question_result_view.dart
  client-app/lib/presentation/view/question/searching/widget/question_search_term_field/question_search_term_field.dart
  client-app/lib/presentation/view/speech_to_text_converter/fragment/complete_speech_analysis_fragment.dart
  client-app/lib/presentation/view/speech_to_text_converter/fragment/recording_speech_fragment.dart
  client-app/lib/presentation/view/speech_to_text_converter/widget/stt_button/stt_button.dart
  client-app/lib/presentation/view/text_to_speech_converter/fragment/complete_text_analysis_fragment.dart
  client-app/lib/presentation/view/text_to_speech_converter/widget/tts_button/tts_button.dart
  client-app/lib/presentation/view_model/article/searching/article_searching_view_model.dart
  client-app/lib/presentation/view_model/comment/adding/comment_adding_view_model.dart
  client-app/lib/presentation/view_model/question/adding/question_adding_view_model.dart
  client-app/lib/presentation/view_model/question/searching/question_searching_view_model.dart
  client-app/lib/presentation/view_model/speech_to_text_converter/speech_to_text_converter_view_model.dart
  client-app/lib/presentation/view_model/text_to_speech_converter/text_to_speech_converter_view_model.dart
  client-app/lib/presentation/widget/article/summary/article_summary_default_item_view.dart
  client-app/lib/presentation/widget/common/text_input/custom_text_form_field.dart
  client-app/pubspec.yaml
Labels: feature ✨

#67 🚑 HotFix - Withdrawal User Cascade with Medication, Question Error
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/domain/mysql/User.java
Labels: hot fix 🚑

#68 🚑 HotFix - User Mapped with Medication, Question
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/user/domain/mysql/User.java
Labels: hot fix 🚑

#72 ✨ Feature - Custom Notification Sound
  client-app/android/app/src/main/res/raw/keep.xml
  client-app/android/app/src/main/res/raw/noti.wav
  client-app/ios/Runner.xcodeproj/project.pbxproj
  client-app/ios/noti.wav
  client-app/pubspec.yaml
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/constant/Constants.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/notification/service/NotificationService.java
Labels: feature ✨

#74 ✨ Feature - Generation API
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/domain/mysql/Article.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/article/domain/mysql/Comment.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/config/SchedulerConfig.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/listener/GenerationListener.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/listener/persistent
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/scheduler/UpdaterScheduler.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/validator/TimeValueValidator.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/domain/mysql/Medication.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/medication/domain/mysql/Schedule.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/domain/mysql/Answer.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/domain/mysql/Question.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/event/CreateQuestionEvent.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/service/CreateAnswerService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/service/CreateQuestionService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/service/DeleteQuestionService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/security/domain/mysql/Account.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/security/service/AuthenticateUserNameService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/tag/domain/mysql/ArticleTag.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/tag/domain/mysql/Tag.java
  server-llm/correction/service.py
  server-llm/correction/views.py
  server-llm/generation/service.py
  server-llm/generation/views.py
Labels: feature ✨

#75 🚑 Hot Fix - Data Length Error & Sign Up Logic Mistake
  client-app/lib/presentation/view_model/login/login_view_model.dart
  client-app/lib/presentation/view_model/sign_up/sign_up_binding.dart
  client-app/lib/presentation/view_model/sign_up/sign_up_view_model.dart
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/domain/mysql/Answer.java
  server-llm/generation/service.py
Labels: hot fix 🚑

#76 🚑 Hot Fix - Korean Prompt Error & UI Mistake
  client-app/lib/presentation/view/question/detail/widget/answer_card/component/answer_default_item_view.dart
  server-llm/generation/service.py
Labels: hot fix 🚑

#77 🚑 Hot Fix - Article UI Error & Push Notification
  client-app/lib/presentation/widget/article/brief/article_brief_default_item_view.dart
  client-app/lib/presentation/widget/article/summary/article_summary_default_item_view.dart
  client-app/pubspec.yaml
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/listener/GenerationListener.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/core/listener/NotificationListener.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/notification/service/NotificationService.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/event/CreateAnswerEvent.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/repository/mysql/QuestionRepository.java
  server-api/src/main/java/org/dongguk/dscd/wooahan/api/question/service/CreateAnswerService.java
Labels: hot fix 🚑
